### ISSUE TITLE
Lesson 19: Writing your own functions

### ISSUE THREAD

**Issue by kelly-sovacool** [GWC-DCMB/ClubCurriculum#8]
Needed for club by 21 Jan. 2020

Files:
- [ ] Lesson Key (`Lessons/_Keys/KEY_LessonXX_Topic.ipynb`)
  - all cells run
- [ ] Lesson notebook (`Lessons/LessonXX_Topic.ipynb`)
  - all cell outputs cleared
- [ ] Practice Key (`Practices/_Keys/KEY_PracticeXX_Topic.ipynb`)
  - all cells run
- [ ] Practice notebook (`Practices/PracticeXX_Topic.ipynb`)
  - all cell outputs cleared

**Comment by zenalapp** [comment]
Written. Need to be edited
